apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: api
          image: bhaumikshukla/re-app
          imagePullPolicy: Always
          env:
           - name: SERVE_PORT
             value: "8080"
           - name: DB_HOST
             value: "mysql"
           - name: DB_PW
             valueFrom:
              secretKeyRef:
                name: {{ .Values.app.db_pw_secret }}
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: app-port
  selector:
    app: web
